### PR TITLE
Vision bounding box

### PR DESCRIPTION
**Pull request by kaathryyn**
Added to detectLandmark() function in vision.js to get boundingPoly values and add to an array called "landmarkInfo". If a landmark has been recognised, the function will return the following array
image

If no landmark is recognised, an empty array will be returned.
image

### CODE REVIEW

**Review by willhtang — CHANGES_REQUESTED** [review]
Would it not be better to return the raw vertices or return them as an array in an array?
The raw data is an array of object [ {x1, y1}, {x2, y2} ].
You can convert this to [ [x1, y1], [x2, y2] ].
The array in an array would be easier for front-end code to interpret without mistakes.

**Comment by kaathryyn** [comment]
Implemented change suggested by Will - detectLandmark() now returns an array of the bounding box coords
image

**Review by willhtang — APPROVED** [review]
Looks good.

**Review by Joel3218 — APPROVED** [review]
All looks good

**Pull request merged**
